name: Security Audit Action
description: "Runs npm audit and creates a GitHub issue if vulnerabilities are found."
inputs:
  node-version:
    description: "Node.js version to use"
    required: true
    default: "18"
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs['node-version'] }}

    - name: Install dependencies
      run: npm install

    - name: Run security audit
      run: |
        npm audit --json > audit-report.json
        echo "Security audit report generated."

    - name: Create GitHub issue if vulnerabilities found
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const fs = require('fs');
          const report = JSON.parse(fs.readFileSync('audit-report.json', 'utf8'));
          const totalDeps = report.metadata?.totalDependencies || 0;
          const totalVulns = report.metadata?.vulnerabilities?.total || 0;

          if (totalDeps > 0 && totalVulns > 0) {
            const message = [
              `Total dependencies: ${totalDeps}`,
              `Total vulnerabilities: ${totalVulns}`,
              '',
              'Please review audit-report.json for details.'
            ].join('\n');

            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '⚠️ Vulnerabilities Found in Dependencies',
              body: message
            });

            console.log('🚨 GitHub issue created.');
          } else {
            console.log('✅ No vulnerabilities found.');
          }
